### ISSUE TITLE
Point interval input resulting in broader output interval?

### ISSUE THREAD

**Issue by etiennebirling** [herbie-fp/rival#9]
Hello,
I am currently working under racket 8.3 and ensures rival is updated to its latest state.
I have observed a behavior I did not expect. While the result for (ival-exp x) does not violate containment requirements, it is inaccurate at an unnecessary level, since the output interval should also be possibly described as a point.
>Welcome to Racket v8.3 [cs].
\> (require math/bigfloat rival)
\> (define x (mk-ival (bf 7.906019208615950103825962123490981785427e77)))
\> (ival-exp x)
(ival (bf "2.098578716467387692404358116883839070632e323228496") +inf.bf)
\> x
(ival (bf #e7.906019208615950103825962123490981785427e77) (bf #e7.906019208615950103825962123490981785427e77))
\> 

Is this behavior intentional or is that actually a potential improvement to make?

**Comment by pavpanchekha** [comment]
(By the way, I am trying to be aggressive about closing issues but I'm happy to continue discussion in this thread or re-open it if further issues are found.)
